### ISSUE TITLE
onInstallConversionDataLoaded don't call to function

### ISSUE THREAD

**Issue by sagishm** [AppsFlyerSDK/PhoneGap#16]
Hi
I try to use in "onInstallConversionDataLoaded" event but i don't get callback.
I'm check the log in XCODE and i get the data but the function to call.

Thanks.

**Comment by af-fess** [comment]
@sagishm  did you register to event `onInstallConversionDataLoaded`like:

    document.addEventListener('onInstallConversionDataLoaded', function(e){
            var attributionData = (JSON.stringify(e.detail));
            alert(attributionData);
        }, false);
