### ISSUE TITLE
Build Error on iOS

### ISSUE THREAD

**Issue by ASGAlex** [AppsFlyerSDK/PhoneGap#17]
Hello!

We have a build error while trying to compile iOS app  with AppsFlyer plugin:

> 1 error generated.
> 
>  BUILD FAILED 
> 
> The following build commands failed:
>         CompileC build/Школа\ Мам.build/Debug-iphonesimulator/Школа\ Мам.build/Objects-normal/i386/AppsFlyerPlugin.o Школа\ Мам/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> Error code 65 for command: xcodebuild with args: -xcconfig,/Users/andrewavsenin/Projects/shkolamam/local/mobile/platforms/ios/cordova/build-debug.xcconfig,-project,Школа Мам.xcodeproj,ARCHS=i386,-target,Школа Мам,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/andrewavsenin/Projects/shkolamam/local/mobile/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/andrewavsenin/Projects/shkolamam/local/mobile/platforms/ios/build/sharedpch
> Error: /Users/andrewavsenin/Projects/shkolamam/local/mobile/platforms/ios/cordova/build: Command failed with exit code 2

Xcode version is 7.3.1
We tried both methods: manual installation, and "cordova plugin add" too.
On the Android version of the app plugin works normal

**Comment by Moussawi7** [comment]
Hi,
Unfortunately, I encountered with same issue:
**cordova version 6.0.0
IOS version 3.9.1**
> Users/apple/Desktop/xxx/platforms/ios/xxxCom/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m:88:13: error:
>       no visible @interface for 'CDVPlugin' declares the selector
>       'webViewEngine'
>     [[super webViewEngine] evaluateJavaScript:[NSString stringWithFormat...
>       ~~~~~ ^~~~~~~~~~~~~
> 1 error generated.
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC build/xxxCom.build/Debug-iphonesimulator/XXXCom.build/Objects-normal/i386/AppsFlyerPlugin.o xxxCom/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> Error code 65 for command: xcodebuild with args: -xcconfig,/Users/apple/Desktop/xxx/platforms/ios/cordova/build-debug.xcconfig,-project,xxxCom.xcodeproj,ARCHS=i386,-target,xxxCom,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/apple/Desktop/xxx/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/apple/Desktop/xxx/platforms/ios/build/sharedpch
> ERROR building one of the platforms: Error: /Users/apple/Desktop/xxx/platforms/ios/cordova/build: Command failed with exit code 2
> You may not have the required environment or OS to build this project
> Error: /Users/apple/Desktop/xxx/platforms/ios/cordova/build: Command failed with exit code 2

**Comment by uareurapid** [comment]
same for me

**Comment by teepark** [comment]
Had the same issue. #20 fixes it for me.

**Comment by uareurapid** [comment]
works for me

**Comment by zigzag-way** [comment]
Also doesnt work:
CompileC build/AppCoins.build/Release-iphoneos/AppCoins.build/Objects-normal/armv7/AppsFlyerPlugin.o AppCoins/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/m1/wl3zc68x40z6cn12m764qkf80000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /project/build/AppCoins.build/Release-iphoneos/AppCoins.build/AppCoins-generated-files.hmap -I/project/build/AppCoins.build/Release-iphoneos/AppCoins.build/AppCoins-own-target-headers.hmap -I/project/build/AppCoins.build/Release-iphoneos/AppCoins.build/AppCoins-all-target-headers.hmap -iquote /project/build/AppCoins.build/Release-iphoneos/AppCoins.build/AppCoins-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build/UninstalledProducts/iphoneos/include -I/project/build -I/project/build/AppCoins.build/Release-iphoneos/AppCoins.build/DerivedSources/armv7 -I/project/build/AppCoins.build/Release-iphoneos/AppCoins.build/DerivedSources -F/project/build -FAppCoins/Plugins/com.phonegap.plugins.facebookconnect -FAppCoins/Plugins/mobi.appcoins.ios-vungle-publisher-adv -include /var/folders/m1/wl3zc68x40z6cn12m764qkf80000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/AppCoins-Prefix-ejjnrldoosfryxghotoxjadvtkut/AppCoins-Prefix.pch -MMD -MT dependencies -MF /project/build/AppCoins.build/Release-iphoneos/AppCoins.build/Objects-normal/armv7/AppsFlyerPlugin.d --serialize-diagnostics /project/build/AppCoins.build/Release-iphoneos/AppCoins.build/Objects-normal/armv7/AppsFlyerPlugin.dia -c /project/AppCoins/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m -o /project/build/AppCoins.build/Release-iphoneos/AppCoins.build/Objects-normal/armv7/AppsFlyerPlugin.o
/project/AppCoins/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m:8:38: error: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
    self = (AppsFlyerPlugin *)[super initWithWebView:theWebView];
                               ~~~~~ ^~~~~~~~~~~~~~~
/project/AppCoins/Plugins/com.appsflyer.phonegap.plugins.appsflyer/AppsFlyerPlugin.m:80:26: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
        [[super webView] stringByEvaluatingJavaScriptFromString: [NSString stringWithFormat:@"javascript:window.plugins.appsFlyer.onInstallConversionDataLoaded(%@)", JSONString]];
         ~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

**Comment by uareurapid** [comment]
@zigzag-way just replace that method by:
`-(void) reportConversionData:(NSString *)data {
    
    NSString *js = [NSString stringWithFormat:@"window.plugins.appsFlyer.onInstallConversionDataLoaded(%@)", data];
    [self.commandDelegate evalJs:js];

}`

**Comment by zigzag-way** [comment]
I can not use your method because I`m using online PhoneGap Build compiler :-(
I hope they will update it soon

**Comment by af-fess** [comment]
Closing as related to [AppsFlyerSDK/PhoneGap#20](https://github.com/AppsFlyerSDK/PhoneGap/pull/20)
