### ISSUE TITLE
"isDebug" Is Set to YES

### ISSUE THREAD

**Issue by Arcticus** [AppsFlyerSDK/PhoneGap#21]
The "isDebug" flag is set to True.  Many users will likely not notice and deploy their app in this mode.  Consider setting to NO and providing an argument that the user can pass in to set it to YES if needed.

**Comment by af-fess** [comment]
will be added in next version

**Comment by af-fess** [comment]
https://github.com/AppsFlyerSDK/PhoneGap#api-methods
