### ISSUE TITLE
Doesn't work with Cordova 6.3.1

### ISSUE THREAD

**Issue by koenoe** [AppsFlyerSDK/PhoneGap#27]
We're trying to use this plugin in our Ionic project, but as soon as we install this Cordova plugin all the other Cordova plugins stop working and we can't click any button anymore in the app. No errors or what so ever..

**Version info:**
Ionic 1.3.1
Ionic CLI 1.7.16
Cordova 6.3.1
Xcode 8.0
iOS 10.0.2

**Comment by Fess-af** [comment]
Hi @koenoe , yes, there is typo in our plugin (JS) part, it's not refers to Cordova 6.3.1

**Comment by koenoe** [comment]
Ok, will this be fixed in a new release?

**Comment by Fess-af** [comment]
yes, in short term. Thanks,
