### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by koenoe** [AppsFlyerSDK/PhoneGap#31]
It's not possible to change the DEBUG flag, it's always on. See:
https://github.com/AppsFlyerSDK/PhoneGap/blob/master/platform/ios/AppsFlyerPlugin.m#L24

It would be nice to enable/disable this via the plugin, because the plugin is flooding the Xcode log.

**Comment by af-fess** [comment]
shortly we will release new build with initSDK with config options  like:
```
var options = {
                       devKey:  'd3Ac9qPnrpXYZxfWmCdpwL',
                       appId: '123456789',
                       isDebug: false
                    };
window.plugins.appsFlyer.initSdk(options, successCB, errorCB);
```

**Comment by koenoe** [comment]
That sounds really good. When can we expect this update?
The plugin in DEBUG mode is not really recommended for our production app.

**Comment by af-fess** [comment]
@koenoe I hope today,

**Comment by koenoe** [comment]
Excellent, thank you so much.

**Comment by af-fess** [comment]
https://github.com/AppsFlyerSDK/PhoneGap#api-methods
