### ISSUE TITLE
onInstallConversionDataLoaded no work in ios

### ISSUE THREAD

**Issue by WilsonFpz** [AppsFlyerSDK/PhoneGap#32]
Hi 
I have a same ionic app publish in appstore/android.
The onInstallConversionDataLoaded attributionData works fine for an android user.
But when an iphone user shows no data.

`document.addEventListener('onInstallConversionDataLoaded', function(e){
        var attributionData = (JSON.stringify(e.detail));
        $localStorage.trackingData = attributionData;
      }, false);
`
any ideas? thanks

**Comment by af-fess** [comment]
@WilsonFpz did you try to debug `-(void)onConversionDataReceived:(NSDictionary*) installData {/*...*/}` line 116. inside `AppsFlyerPlugin.m` ?

**Comment by lalmanzar** [comment]
@af-fess I have an issue with the onInstallConversionDataLoaded on ios. It is always reporting as organic. But on the dashboard is tracked correctly as a non-organic and all the other fields like the campaign, also on the raw install export is reported correctly. The issue is only with ios, android is reported correctly. Any idea what might be the issue?

Thanks

**Comment by af-fess** [comment]
@lalmanzar it looks weird, how did you test non-organic install, please give more details.

**Comment by lalmanzar** [comment]
@af-fess 
In the config.xml I have:
`<plugin name="appsflyer" version="4.2.8"/>`
in my main.js I have this inside the device ready:
`var args = {
        devKey: 'aanexxxxxxxxxxxxxxxxxxxxxxxx'
    };`
    `var userAgent = window.navigator.userAgent.toLowerCase();`
   ` if (/iphone|ipad|ipod/.test( userAgent )) {`
   `     args.appId = "id11111111111";           `
  `  }`
 `   window.plugins.appsFlyer.initSdk(args);`

and this at the end:
`document.addEventListener('onInstallConversionDataLoaded', function(e){`
 `   var attributionData = e.detail;`
`    alert(JSON.stringify(attributionData));`
`}, false);`

Then I build the app using phonegap Build (I don't have a ios machine to do the build).
For the steps I use for testing, I first click the custom like I have with a campaing and some extra parameters that I'll need, after that I install the IPA and open the app. In the dashboard I can see the click and install of the custom campaing but the app shows this in the alert :
`{"af_status":"Organic","af_message":"organic install"}`

I also tried with the sdk of the new repository and have the same issue.

**Comment by af-fess** [comment]
@lalmanzar we migrated your issue to new repository: [cordova-plugin-appsflyer-sdk/issues/1](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/issues/1)

**Comment by af-fess** [comment]
@lalmanzar  also notice, in new repository [cordova-plugin-appsflyer-sdk](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk)  we removed `addEventListener('onInstallConversionDataLoaded')` and added flag instead: `onInstallConversionDataListener:true`. You should get attribution data in `onSuccess` callback in `initSdk` method.

**Comment by lalmanzar** [comment]
@af-fess yes, I noticed. But I still got the {"af_status":"Organic","af_message":"organic install"} inside the result.data .
