### ISSUE TITLE
Installation error via NPM

### ISSUE THREAD

**Issue by koenoe** [AppsFlyerSDK/PhoneGap#33]
If I use the command:
```
cordova plugin add appsflyer --save
```

I get the following error:
```
Fetching plugin "com.appsflyer.phonegap.plugins.appsflyer@~4.2.4" via npm

Failed to restore plugin "com.appsflyer.phonegap.plugins.appsflyer" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin com.appsflyer.phonegap.plugins.appsflyer@~4.2.4 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.appsflyer.phonegap.plugins.appsflyer
```

**Comment by af-fess** [comment]
@koenoe did you try to install other plugin over `npm`? looks like its connectivity problem. I created new cordova project + platforms and added appsflyer plugin. everything works as expected. 

What you get if you install plugin from git: `cordova plugin add https://github.com/AppsFlyerSDK/PhoneGap.git`?

**Comment by af-fess** [comment]
@koenoe also please post output  with debug mode:
`cordova plugin add appsflyer --save -d`

**Comment by koenoe** [comment]
@af-fess It works now. I don't know why, because I was able to install other plugins via NPM when I created this issue.

**Comment by af-fess** [comment]
ok, great,

**Comment by koenoe** [comment]
This problem is back. It works when I install the plugin via:
```
cordova plugin add appsflyer -- save
```

But when I install it from the 'config.xml', this error pops up.

```
npm
http 404 https://registry.npmjs.org/com.appsflyer.phonegap.plugins.appsflyer

Failed to restore plugin "com.appsflyer.phonegap.plugins.appsflyer" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin com.appsflyer.phonegap.plugins.appsflyer@~4.2.8 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.appsflyer.phonegap.plugins.appsflyer
```

If you click the link: https://registry.npmjs.org/com.appsflyer.phonegap.plugins.appsflyer you'll see it returns a 404.

All other plugins installed via NPM are working fine.

**Comment by af-fess** [comment]
@koenoe what exactly do you run to install from `config.xml`?  

The `com.appsflyer.phonegap.plugins.appsflyer` is taken from plugin id that not equals to `npm` name.
Actually the registry should be like: [https://registry.npmjs.org/appsflyer](https://registry.npmjs.org/appsflyer). Anyways we will change plugin name to solve similar behaviour

**Comment by koenoe** [comment]
`ionic platform add ios android` or `cordova platform add ios android`

**Comment by af-fess** [comment]
@koenoe can you please post your `config.xml`

**Comment by koenoe** [comment]
@af-fess this is the relevant part of our config.xml:

```
    <engine name="ios" spec="4.3.0" />
    <engine name="android" spec="6.1.0" />
    <engine name="browser" spec="4.1.0" />
    <plugin name="cordova-plugin-console" spec="1.0.4" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.0" />
    <plugin name="cordova-plugin-splashscreen" spec="4.0.0" />
    <plugin name="cordova-plugin-statusbar" spec="2.2.0" />
    <plugin name="ionic-plugin-keyboard" spec="2.0.1" />
    <plugin name="cordova-plugin-dialogs" spec="1.3.0" />
    <plugin name="cordova-plugin-network-information" spec="1.3.0" />
    <plugin name="cordova-plugin-google-analytics" spec="1.0.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="1.5.0" />
    <plugin name="cordova-plugin-x-socialsharing" spec="5.1.3" />
    <plugin name="phonegap-plugin-push" spec="1.9.0">
        <variable name="SENDER_ID" value="xxx" />
    </plugin>
    <plugin name="cordova-plugin-device" spec="1.1.3" />
    <plugin name="cordova-plugin-insomnia" spec="4.2.0" />
    <plugin name="cordova-plugin-appavailability" spec="0.4.1" />
    <plugin name="cordova-plugin-nativestorage" spec="2.1.0" />
    <plugin name="cordova-clipboard" spec="1.0.0" />
    <plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" spec="3.2.1" />
    <plugin name="com.appsflyer.phonegap.plugins.appsflyer" spec="4.2.8" />
```

**Comment by koenoe** [comment]
Any news on this?

**Comment by af-fess** [comment]
@koenoe hey, This framework is deprecated. We released before 2 weeks new plugin [cordova-plugin-appsflyer-sdk](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk).. Your problem should be resolved.
